version: '3'

networks:
  mmpe:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16

services:

  mmpe-ipe:
    image: 'dfki/mmpe-ipe:1.0.0'
    networks:
      - mmpe
    container_name: mmpe-ipe
    restart: always

  mmpe-core:
    depends_on:
      - mmpe-ipe
    image: 'dfki/mmpe-core:1.0.0'
    networks:
      - mmpe
    container_name: mmpe-core
    restart: always
    volumes:
      - './mmpe-server/data/projects:/usr/src/app/data/projects'
      - './mmpe-server/config.json:/usr/src/app/config.json:ro'
      - './mmpe-frontend/src/assets/config.json:/usr/share/nginx/html/assets/config.json:ro'
    environment:
      - IPE_URL=http://mmpe-ipe:8000/api/alternatives
    ports:
      - '80:80'
      - '443:443'
      - '3000:3000'
      - '3002:3002'
