version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  express: #name of the service
    build: mmpe-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding